apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: codegen-sep4-2
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/maysunfaisal/codegen-sep4-2:fdb74635d0ebcb755304abba2a6458bdf1bf393a@sha256:8fc335aa1517833d822600f9341523b83e8a915fb95ee51a425fcfa9310ada9c # use pre-built to bootstrap 
          name: app-inference
